apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-blue
  labels:
    app: auth-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
      version: blue
  template:
    metadata:
      labels:
        app: auth
        version: blue
    spec:
      containers:
        - name: auth-container
          image: auth:blue
          ports:
            - containerPort: 8080