apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: NodePort
  selector:
    app: auth
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: 8080
