apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-blue
  labels:
    app: chat-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
      version: blue
  template:
    metadata:
      labels:
        app: chat
        version: blue
    spec:
      containers:
        - name: chat-container
          image: chat:blue
          ports:
            - containerPort: 8080