apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  type: NodePort
  selector:
    app: chat
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: 8080
