// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/proto/v1/friendship/service.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_v1_friendship_service_proto protoreflect.FileDescriptor

const file_api_proto_v1_friendship_service_proto_rawDesc = "" +
	"\n" +
	"%api/proto/v1/friendship/service.proto\x12/github.com.nazarovnick.chat_platform.friendship\x1a&api/proto/v1/friendship/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xd6\a\n" +
	"\x11FriendshipService\x12\xbc\x01\n" +
	"\rRequestFriend\x12B.github.com.nazarovnick.chat_platform.friendship.SendFriendRequest\x1aC.github.com.nazarovnick.chat_platform.friendship.SendFriendResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/friends/request\x12\xbe\x01\n" +
	"\fAcceptFriend\x12D.github.com.nazarovnick.chat_platform.friendship.AcceptFriendRequest\x1aE.github.com.nazarovnick.chat_platform.friendship.AcceptFriendResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/friends/accept\x12\xc2\x01\n" +
	"\rDeclineFriend\x12E.github.com.nazarovnick.chat_platform.friendship.DeclineFriendRequest\x1aF.github.com.nazarovnick.chat_platform.friendship.DeclineFriendResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/friends/decline\x12\xbe\x01\n" +
	"\fRemoveFriend\x12D.github.com.nazarovnick.chat_platform.friendship.RemoveFriendRequest\x1aE.github.com.nazarovnick.chat_platform.friendship.RemoveFriendResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/friends/remove\x12\xba\x01\n" +
	"\n" +
	"GetFriends\x12B.github.com.nazarovnick.chat_platform.friendship.GetFriendsRequest\x1aC.github.com.nazarovnick.chat_platform.friendship.GetFriendsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/friends/{user_uuid}B\x94\x03\x92A\xfd\x02\x12\x8e\x02\n" +
	"\x16Friendship Service API\x12~API for managing friendship interactions between users, including sending, accepting, declining, and removing friend requests.\"9\n" +
	"\x17Friendship Service Team\x12\x1ehttps://github.com/nazarovnick*2\n" +
	"\vMIT License\x12#https://opensource.org/licenses/MIT2\x051.0.0*\x02\x01\x02rf\n" +
	"\"Full documentation and source code\x12@https://github.com/nazarovnick/chat-platform/services/friendshipZ\x11/friendship/v1;v1b\x06proto3"

var file_api_proto_v1_friendship_service_proto_goTypes = []any{
	(*SendFriendRequest)(nil),     // 0: github.com.nazarovnick.chat_platform.friendship.SendFriendRequest
	(*AcceptFriendRequest)(nil),   // 1: github.com.nazarovnick.chat_platform.friendship.AcceptFriendRequest
	(*DeclineFriendRequest)(nil),  // 2: github.com.nazarovnick.chat_platform.friendship.DeclineFriendRequest
	(*RemoveFriendRequest)(nil),   // 3: github.com.nazarovnick.chat_platform.friendship.RemoveFriendRequest
	(*GetFriendsRequest)(nil),     // 4: github.com.nazarovnick.chat_platform.friendship.GetFriendsRequest
	(*SendFriendResponse)(nil),    // 5: github.com.nazarovnick.chat_platform.friendship.SendFriendResponse
	(*AcceptFriendResponse)(nil),  // 6: github.com.nazarovnick.chat_platform.friendship.AcceptFriendResponse
	(*DeclineFriendResponse)(nil), // 7: github.com.nazarovnick.chat_platform.friendship.DeclineFriendResponse
	(*RemoveFriendResponse)(nil),  // 8: github.com.nazarovnick.chat_platform.friendship.RemoveFriendResponse
	(*GetFriendsResponse)(nil),    // 9: github.com.nazarovnick.chat_platform.friendship.GetFriendsResponse
}
var file_api_proto_v1_friendship_service_proto_depIdxs = []int32{
	0, // 0: github.com.nazarovnick.chat_platform.friendship.FriendshipService.RequestFriend:input_type -> github.com.nazarovnick.chat_platform.friendship.SendFriendRequest
	1, // 1: github.com.nazarovnick.chat_platform.friendship.FriendshipService.AcceptFriend:input_type -> github.com.nazarovnick.chat_platform.friendship.AcceptFriendRequest
	2, // 2: github.com.nazarovnick.chat_platform.friendship.FriendshipService.DeclineFriend:input_type -> github.com.nazarovnick.chat_platform.friendship.DeclineFriendRequest
	3, // 3: github.com.nazarovnick.chat_platform.friendship.FriendshipService.RemoveFriend:input_type -> github.com.nazarovnick.chat_platform.friendship.RemoveFriendRequest
	4, // 4: github.com.nazarovnick.chat_platform.friendship.FriendshipService.GetFriends:input_type -> github.com.nazarovnick.chat_platform.friendship.GetFriendsRequest
	5, // 5: github.com.nazarovnick.chat_platform.friendship.FriendshipService.RequestFriend:output_type -> github.com.nazarovnick.chat_platform.friendship.SendFriendResponse
	6, // 6: github.com.nazarovnick.chat_platform.friendship.FriendshipService.AcceptFriend:output_type -> github.com.nazarovnick.chat_platform.friendship.AcceptFriendResponse
	7, // 7: github.com.nazarovnick.chat_platform.friendship.FriendshipService.DeclineFriend:output_type -> github.com.nazarovnick.chat_platform.friendship.DeclineFriendResponse
	8, // 8: github.com.nazarovnick.chat_platform.friendship.FriendshipService.RemoveFriend:output_type -> github.com.nazarovnick.chat_platform.friendship.RemoveFriendResponse
	9, // 9: github.com.nazarovnick.chat_platform.friendship.FriendshipService.GetFriends:output_type -> github.com.nazarovnick.chat_platform.friendship.GetFriendsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_friendship_service_proto_init() }
func file_api_proto_v1_friendship_service_proto_init() {
	if File_api_proto_v1_friendship_service_proto != nil {
		return
	}
	file_api_proto_v1_friendship_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_friendship_service_proto_rawDesc), len(file_api_proto_v1_friendship_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_friendship_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_friendship_service_proto_depIdxs,
	}.Build()
	File_api_proto_v1_friendship_service_proto = out.File
	file_api_proto_v1_friendship_service_proto_goTypes = nil
	file_api_proto_v1_friendship_service_proto_depIdxs = nil
}
