apiVersion: v1
kind: Service
metadata:
  name: friendship-service
  labels:
    app: friendship-service
spec:
  type: NodePort
  selector:
    app: friendship
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: 8080
