// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/proto/v1/user/messages.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age           uint32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birth_date,proto3" json:"birth_date,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,proto3" json:"avatar_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	SoftDeleted   bool                   `protobuf:"varint,7,opt,name=soft_deleted,proto3" json:"soft_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetUserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserResponse) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *GetUserResponse) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *GetUserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *GetUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetUserResponse) GetSoftDeleted() bool {
	if x != nil {
		return x.SoftDeleted
	}
	return false
}

type GetUserByNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByNicknameRequest) Reset() {
	*x = GetUserByNicknameRequest{}
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByNicknameRequest) ProtoMessage() {}

func (x *GetUserByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByNicknameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type GetUserByNicknameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age           uint32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birth_date,proto3" json:"birth_date,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,proto3" json:"avatar_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	SoftDeleted   bool                   `protobuf:"varint,7,opt,name=soft_deleted,proto3" json:"soft_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByNicknameResponse) Reset() {
	*x = GetUserByNicknameResponse{}
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByNicknameResponse) ProtoMessage() {}

func (x *GetUserByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByNicknameResponse.ProtoReflect.Descriptor instead.
func (*GetUserByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByNicknameResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetUserByNicknameResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserByNicknameResponse) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *GetUserByNicknameResponse) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *GetUserByNicknameResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *GetUserByNicknameResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetUserByNicknameResponse) GetSoftDeleted() bool {
	if x != nil {
		return x.SoftDeleted
	}
	return false
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserUuid      string                  `protobuf:"bytes,1,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	Nickname      *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	BirthDate     *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=birth_date,proto3" json:"birth_date,omitempty"`
	AvatarUrl     *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=avatar_url,proto3" json:"avatar_url,omitempty"`
	SoftDeleted   *wrapperspb.BoolValue   `protobuf:"bytes,5,opt,name=soft_deleted,proto3" json:"soft_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserRequest) GetNickname() *wrapperspb.StringValue {
	if x != nil {
		return x.Nickname
	}
	return nil
}

func (x *UpdateUserRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *UpdateUserRequest) GetAvatarUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.AvatarUrl
	}
	return nil
}

func (x *UpdateUserRequest) GetSoftDeleted() *wrapperspb.BoolValue {
	if x != nil {
		return x.SoftDeleted
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age           uint32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birth_date,proto3" json:"birth_date,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,proto3" json:"avatar_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	SoftDeleted   bool                   `protobuf:"varint,7,opt,name=soft_deleted,proto3" json:"soft_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UpdateUserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserResponse) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateUserResponse) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *UpdateUserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateUserResponse) GetSoftDeleted() bool {
	if x != nil {
		return x.SoftDeleted
	}
	return false
}

type SearchUsersByNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersByNicknameRequest) Reset() {
	*x = SearchUsersByNicknameRequest{}
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersByNicknameRequest) ProtoMessage() {}

func (x *SearchUsersByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersByNicknameRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SearchUsersByNicknameRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersByNicknameRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchUsersByNicknameRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchUsersByNicknameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersByNicknameResponse) Reset() {
	*x = SearchUsersByNicknameResponse{}
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersByNicknameResponse) ProtoMessage() {}

func (x *SearchUsersByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersByNicknameResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SearchUsersByNicknameResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age           uint32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birth_date,proto3" json:"birth_date,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,proto3" json:"avatar_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	SoftDeleted   bool                   `protobuf:"varint,7,opt,name=soft_deleted,proto3" json:"soft_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_messages_proto_rawDescGZIP(), []int{8}
}

func (x *User) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetSoftDeleted() bool {
	if x != nil {
		return x.SoftDeleted
	}
	return false
}

var File_api_proto_v1_user_messages_proto protoreflect.FileDescriptor

const file_api_proto_v1_user_messages_proto_rawDesc = "" +
	"\n" +
	" api/proto/v1/user/messages.proto\x12)github.com.nazarovnick.chat_platform.user\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x85\x03\n" +
	"\x0eGetUserRequest\x12\xbe\x01\n" +
	"\tuser_uuid\x18\x01 \x01(\tB\x9f\x01\x92A\x90\x01*\x1dUUID пользователя2oUUID пользователя, по которому необходимо получить информацию\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tuser_uuid:\xb1\x01\x92A\xad\x01\n" +
	"\xaa\x01*\x0eGetUserRequest2UЗапрос на получение информации о пользователеJ5{\"user_uuid\": \"d290f1ee-6c54-4b01-90e6-d701748f0851\"}\xd2\x01\tuser_uuid\"\xe4\f\n" +
	"\x0fGetUserResponse\x12|\n" +
	"\tuser_uuid\x18\x01 \x01(\tB^\x92AP*\x04UUID2HУникальный идентификатор пользователя\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tuser_uuid\x12\xae\x01\n" +
	"\bnickname\x18\x02 \x01(\tB\x91\x01\x92Aq*\x0eНикнейм2_Уникальное имя пользователя, отображаемое публично\xbaH\x1a\xc8\x01\x01r\x15\x10\x03\x18 2\x0f^[a-zA-Z0-9_]+$R\bnickname\x12\xaf\x01\n" +
	"\x03age\x18\x03 \x01(\rB\x9c\x01\x92A\x8e\x01*'Возраст пользователя2cЦелое число, указывающее возраст пользователя в годах\xbaH\a\xc8\x01\x01*\x02(\x00R\x03age\x12\xb2\x01\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBv\x92Ah*2Дата рождения пользователя22Дата рождения пользователя\xbaH\b\xc8\x01\x01\xb2\x01\x028\x01R\n" +
	"birth_date\x12\x9a\x01\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tBz\x92Ao*\x1eСсылка на аватар2MURL-адрес изображения профиля пользователя\xbaH\x05r\x03\x88\x01\x01R\n" +
	"avatar_url\x12\xc2\x01\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x85\x01\x92Aw*2Дата создания пользователя2AДата создания профиля пользователя\xbaH\b\xc8\x01\x01\xb2\x01\x028\x01R\n" +
	"created_at\x12\xe2\x01\n" +
	"\fsoft_deleted\x18\a \x01(\bB\xbd\x01\x92A\xb9\x01*(Флаг мягкого удаления2\x8c\x01Если true — пользователь считается удалённым, но физически остаётся в системеR\fsoft_deleted:\xf3\x02\x92A\xef\x02\n" +
	"\xec\x02*\x0fGetUserResponse2cОтвет на запрос о получении информации о пользователеJ\xf3\x01{\"user_uuid\": \"123e4567-e89b-12d3-a456-426614174000\",\n" +
	"\"nickname\": \"vasyan888\",\n" +
	"\"age\": 30,\n" +
	"\"birth_date\": \"1993-05-21T00:00:00Z\",\n" +
	"\"avatar_url\": \"https://kakoi-to-sait.com/avatar.png\",\n" +
	"\"created_at\": \"2024-01-01T10:00:00Z\",\n" +
	"\"soft_deleted\": false\n" +
	"}\"\xd6\x04\n" +
	"\x18GetUserByNicknameRequest\x12\xae\x01\n" +
	"\bnickname\x18\x01 \x01(\tB\x91\x01\x92Aq*\x0eНикнейм2_Уникальное имя пользователя, отображаемое публично\xbaH\x1a\xc8\x01\x01r\x15\x10\x03\x18 2\x0f^[a-zA-Z0-9_]+$R\bnickname:\x88\x03\x92A\x84\x03\n" +
	"\x81\x03*\x11GetUserByNickname2kЗапрос на получение информации о пользователе по никнеймуJ\xf3\x01{\"user_uuid\": \"123e4567-e89b-12d3-a456-426614174000\",\n" +
	"\"nickname\": \"vasyan888\",\n" +
	"\"age\": 30,\n" +
	"\"birth_date\": \"1993-05-21T00:00:00Z\",\n" +
	"\"avatar_url\": \"https://kakoi-to-sait.com/avatar.png\",\n" +
	"\"created_at\": \"2024-01-01T10:00:00Z\",\n" +
	"\"soft_deleted\": false\n" +
	"}\xd2\x01\bnickname\"\x8e\r\n" +
	"\x19GetUserByNicknameResponse\x12|\n" +
	"\tuser_uuid\x18\x01 \x01(\tB^\x92AP*\x04UUID2HУникальный идентификатор пользователя\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tuser_uuid\x12\xae\x01\n" +
	"\bnickname\x18\x02 \x01(\tB\x91\x01\x92Aq*\x0eНикнейм2_Уникальное имя пользователя, отображаемое публично\xbaH\x1a\xc8\x01\x01r\x15\x10\x03\x18 2\x0f^[a-zA-Z0-9_]+$R\bnickname\x12\xaf\x01\n" +
	"\x03age\x18\x03 \x01(\rB\x9c\x01\x92A\x8e\x01*'Возраст пользователя2cЦелое число, указывающее возраст пользователя в годах\xbaH\a\xc8\x01\x01*\x02(\x00R\x03age\x12\xb2\x01\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBv\x92Ah*2Дата рождения пользователя22Дата рождения пользователя\xbaH\b\xc8\x01\x01\xb2\x01\x028\x01R\n" +
	"birth_date\x12\x9a\x01\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tBz\x92Ao*\x1eСсылка на аватар2MURL-адрес изображения профиля пользователя\xbaH\x05r\x03\x88\x01\x01R\n" +
	"avatar_url\x12\xc2\x01\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x85\x01\x92Aw*2Дата создания пользователя2AДата создания профиля пользователя\xbaH\b\xc8\x01\x01\xb2\x01\x028\x01R\n" +
	"created_at\x12\xe2\x01\n" +
	"\fsoft_deleted\x18\a \x01(\bB\xbd\x01\x92A\xb9\x01*(Флаг мягкого удаления2\x8c\x01Если true — пользователь считается удалённым, но физически остаётся в системеR\fsoft_deleted:\x93\x03\x92A\x8f\x03\n" +
	"\x8c\x03*\x19GetUserByNicknameResponse2yОтвет на запрос о получении информации о пользователе по никнеймуJ\xf3\x01{\"user_uuid\": \"123e4567-e89b-12d3-a456-426614174000\",\n" +
	"\"nickname\": \"vasyan888\",\n" +
	"\"age\": 30,\n" +
	"\"birth_date\": \"1993-05-21T00:00:00Z\",\n" +
	"\"avatar_url\": \"https://kakoi-to-sait.com/avatar.png\",\n" +
	"\"created_at\": \"2024-01-01T10:00:00Z\",\n" +
	"\"soft_deleted\": false\n" +
	"}\"\xe0\n" +
	"\n" +
	"\x11UpdateUserRequest\x12|\n" +
	"\tuser_uuid\x18\x01 \x01(\tB^\x92AP*\x04UUID2HУникальный идентификатор пользователя\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tuser_uuid\x12\xcc\x01\n" +
	"\bnickname\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB\x91\x01\x92Aq*\x0eНикнейм2_Уникальное имя пользователя, отображаемое публично\xbaH\x1a\xc8\x01\x01r\x15\x10\x03\x18 2\x0f^[a-zA-Z0-9_]+$R\bnickname\x12\xb2\x01\n" +
	"\n" +
	"birth_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampBv\x92Ah*2Дата рождения пользователя22Дата рождения пользователя\xbaH\b\xc8\x01\x01\xb2\x01\x028\x01R\n" +
	"birth_date\x12\xb8\x01\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueBz\x92Ao*\x1eСсылка на аватар2MURL-адрес изображения профиля пользователя\xbaH\x05r\x03\x88\x01\x01R\n" +
	"avatar_url\x12\xfe\x01\n" +
	"\fsoft_deleted\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueB\xbd\x01\x92A\xb9\x01*(Флаг мягкого удаления2\x8c\x01Если true — пользователь считается удалённым, но физически остаётся в системеR\fsoft_deleted:\x8c\x03\x92A\x88\x03\n" +
	"\x85\x03*\x11UpdateUserRequest2\x9a\x02Запрос на обновление профиля пользователя.\n" +
	"Позволяет изменить один или несколько полей профиля: никнейм, дату рождения, аватар и статус мягкого удаления.JS{\"user_uuid\": \"123e4567-e89b-12d3-a456-426614174000\",\n" +
	"\"nickname\": \"SuperVasyan888\"}\"\xe5\f\n" +
	"\x12UpdateUserResponse\x12|\n" +
	"\tuser_uuid\x18\x01 \x01(\tB^\x92AP*\x04UUID2HУникальный идентификатор пользователя\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tuser_uuid\x12\xae\x01\n" +
	"\bnickname\x18\x02 \x01(\tB\x91\x01\x92Aq*\x0eНикнейм2_Уникальное имя пользователя, отображаемое публично\xbaH\x1a\xc8\x01\x01r\x15\x10\x03\x18 2\x0f^[a-zA-Z0-9_]+$R\bnickname\x12\xaf\x01\n" +
	"\x03age\x18\x03 \x01(\rB\x9c\x01\x92A\x8e\x01*'Возраст пользователя2cЦелое число, указывающее возраст пользователя в годах\xbaH\a\xc8\x01\x01*\x02(\x00R\x03age\x12\xb2\x01\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBv\x92Ah*2Дата рождения пользователя22Дата рождения пользователя\xbaH\b\xc8\x01\x01\xb2\x01\x028\x01R\n" +
	"birth_date\x12\x9a\x01\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tBz\x92Ao*\x1eСсылка на аватар2MURL-адрес изображения профиля пользователя\xbaH\x05r\x03\x88\x01\x01R\n" +
	"avatar_url\x12\xc2\x01\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x85\x01\x92Aw*2Дата создания пользователя2AДата создания профиля пользователя\xbaH\b\xc8\x01\x01\xb2\x01\x028\x01R\n" +
	"created_at\x12\xe2\x01\n" +
	"\fsoft_deleted\x18\a \x01(\bB\xbd\x01\x92A\xb9\x01*(Флаг мягкого удаления2\x8c\x01Если true — пользователь считается удалённым, но физически остаётся в системеR\fsoft_deleted:\xf1\x02\x92A\xed\x02\n" +
	"\xea\x02*\x12UpdateUserResponse2YОтвет на запрос обновления профиля пользователяJ\xf8\x01{\"user_uuid\": \"123e4567-e89b-12d3-a456-426614174000\",\n" +
	"\"nickname\": \"SuperVasyan888\",\n" +
	"\"age\": 30,\n" +
	"\"birth_date\": \"1993-05-21T00:00:00Z\",\n" +
	"\"avatar_url\": \"https://kakoi-to-sait.com/avatar.png\",\n" +
	"\"created_at\": \"2024-01-01T10:00:00Z\",\n" +
	"\"soft_deleted\": false\n" +
	"}\"\x83\x06\n" +
	"\x1cSearchUsersByNicknameRequest\x12\xbd\x01\n" +
	"\x05query\x18\x01 \x01(\tB\xa6\x01\x92A\x98\x01*\x1fПоисковый запрос2uЧасть никнейма, по которому осуществляется поиск пользователей\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x05query\x12\xc6\x01\n" +
	"\x05limit\x18\x02 \x01(\rB\xaf\x01\x92A\xa4\x01*+Ограничение количества2uМаксимальное количество пользователей в ответе (по умолчанию 10)\xbaH\x04*\x02\x18dR\x05limit\x12\xa7\x01\n" +
	"\x06offset\x18\x03 \x01(\rB\x8e\x01\x92A\x83\x01*\x10Смещение2oКоличество записей, которые нужно пропустить (для пагинации)\xbaH\x04*\x02(\x00R\x06offset:\xaf\x01\x92A\xab\x01\n" +
	"\xa8\x01*\x1cSearchUsersByNicknameRequest2XЗапрос на поиск пользователей по части никнеймаJ.{\"query\": \"vasya\",\n" +
	"\"limit\": 20,\n" +
	"\"offset\": 50\n" +
	"}\"\xec\a\n" +
	"\x1dSearchUsersByNicknameResponse\x12\xe2\x01\n" +
	"\x05users\x18\x01 \x03(\v2/.github.com.nazarovnick.chat_platform.user.UserB\x9a\x01\x92A\x96\x01*'Список пользователей2kРезультат поиска — пользователи, соответствующие запросуR\x05users:\xe5\x05\x92A\xe1\x05\n" +
	"\xde\x05*\x1dSearchUsersByNicknameResponse2eОтвет на запрос поиска пользователей по части никнеймаJ\xd5\x04{\n" +
	"  \"users\": [\n" +
	"    {\n" +
	"      \"user_uuid\": \"11111111-1111-1111-1111-111111111111\",\n" +
	"      \"nickname\": \"vasyan1\",\n" +
	"      \"age\": 27,\n" +
	"      \"birth_date\": \"1996-08-15T00:00:00Z\",\n" +
	"      \"avatar_url\": \"https://example.com/avatar1.png\",\n" +
	"      \"created_at\": \"2023-01-01T12:00:00Z\",\n" +
	"      \"soft_deleted\": false\n" +
	"    },\n" +
	"    {\n" +
	"      \"user_uuid\": \"22222222-2222-2222-2222-222222222222\",\n" +
	"      \"nickname\": \"vasyan2\",\n" +
	"      \"age\": 31,\n" +
	"      \"birth_date\": \"1993-04-12T00:00:00Z\",\n" +
	"      \"avatar_url\": \"https://example.com/avatar2.png\",\n" +
	"      \"created_at\": \"2022-06-10T10:30:00Z\",\n" +
	"      \"soft_deleted\": false\n" +
	"    }\n" +
	"  ]\n" +
	"}\"\xd2\f\n" +
	"\x04User\x12|\n" +
	"\tuser_uuid\x18\x01 \x01(\tB^\x92AP*\x04UUID2HУникальный идентификатор пользователя\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tuser_uuid\x12\xae\x01\n" +
	"\bnickname\x18\x02 \x01(\tB\x91\x01\x92Aq*\x0eНикнейм2_Уникальное имя пользователя, отображаемое публично\xbaH\x1a\xc8\x01\x01r\x15\x10\x03\x18 2\x0f^[a-zA-Z0-9_]+$R\bnickname\x12\xaf\x01\n" +
	"\x03age\x18\x03 \x01(\rB\x9c\x01\x92A\x8e\x01*'Возраст пользователя2cЦелое число, указывающее возраст пользователя в годах\xbaH\a\xc8\x01\x01*\x02(\x00R\x03age\x12\xb2\x01\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBv\x92Ah*2Дата рождения пользователя22Дата рождения пользователя\xbaH\b\xc8\x01\x01\xb2\x01\x028\x01R\n" +
	"birth_date\x12\x9a\x01\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tBz\x92Ao*\x1eСсылка на аватар2MURL-адрес изображения профиля пользователя\xbaH\x05r\x03\x88\x01\x01R\n" +
	"avatar_url\x12\xc2\x01\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x85\x01\x92Aw*2Дата создания пользователя2AДата создания профиля пользователя\xbaH\b\xc8\x01\x01\xb2\x01\x028\x01R\n" +
	"created_at\x12\xe2\x01\n" +
	"\fsoft_deleted\x18\a \x01(\bB\xbd\x01\x92A\xb9\x01*(Флаг мягкого удаления2\x8c\x01Если true — пользователь считается удалённым, но физически остаётся в системеR\fsoft_deleted:\xec\x02\x92A\xe8\x02\n" +
	"\xe5\x02*\x04User2gМодель пользователя, содержащая основные сведения о нёмJ\xf3\x01{\"user_uuid\": \"123e4567-e89b-12d3-a456-426614174000\",\n" +
	"\"nickname\": \"vasyan888\",\n" +
	"\"age\": 30,\n" +
	"\"birth_date\": \"1993-05-21T00:00:00Z\",\n" +
	"\"avatar_url\": \"https://kakoi-to-sait.com/avatar.png\",\n" +
	"\"created_at\": \"2024-01-01T10:00:00Z\",\n" +
	"\"soft_deleted\": false\n" +
	"}B\rZ\v/user/v1;v1b\x06proto3"

var (
	file_api_proto_v1_user_messages_proto_rawDescOnce sync.Once
	file_api_proto_v1_user_messages_proto_rawDescData []byte
)

func file_api_proto_v1_user_messages_proto_rawDescGZIP() []byte {
	file_api_proto_v1_user_messages_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_user_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_user_messages_proto_rawDesc), len(file_api_proto_v1_user_messages_proto_rawDesc)))
	})
	return file_api_proto_v1_user_messages_proto_rawDescData
}

var file_api_proto_v1_user_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_v1_user_messages_proto_goTypes = []any{
	(*GetUserRequest)(nil),                // 0: github.com.nazarovnick.chat_platform.user.GetUserRequest
	(*GetUserResponse)(nil),               // 1: github.com.nazarovnick.chat_platform.user.GetUserResponse
	(*GetUserByNicknameRequest)(nil),      // 2: github.com.nazarovnick.chat_platform.user.GetUserByNicknameRequest
	(*GetUserByNicknameResponse)(nil),     // 3: github.com.nazarovnick.chat_platform.user.GetUserByNicknameResponse
	(*UpdateUserRequest)(nil),             // 4: github.com.nazarovnick.chat_platform.user.UpdateUserRequest
	(*UpdateUserResponse)(nil),            // 5: github.com.nazarovnick.chat_platform.user.UpdateUserResponse
	(*SearchUsersByNicknameRequest)(nil),  // 6: github.com.nazarovnick.chat_platform.user.SearchUsersByNicknameRequest
	(*SearchUsersByNicknameResponse)(nil), // 7: github.com.nazarovnick.chat_platform.user.SearchUsersByNicknameResponse
	(*User)(nil),                          // 8: github.com.nazarovnick.chat_platform.user.User
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),        // 10: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),          // 11: google.protobuf.BoolValue
}
var file_api_proto_v1_user_messages_proto_depIdxs = []int32{
	9,  // 0: github.com.nazarovnick.chat_platform.user.GetUserResponse.birth_date:type_name -> google.protobuf.Timestamp
	9,  // 1: github.com.nazarovnick.chat_platform.user.GetUserResponse.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: github.com.nazarovnick.chat_platform.user.GetUserByNicknameResponse.birth_date:type_name -> google.protobuf.Timestamp
	9,  // 3: github.com.nazarovnick.chat_platform.user.GetUserByNicknameResponse.created_at:type_name -> google.protobuf.Timestamp
	10, // 4: github.com.nazarovnick.chat_platform.user.UpdateUserRequest.nickname:type_name -> google.protobuf.StringValue
	9,  // 5: github.com.nazarovnick.chat_platform.user.UpdateUserRequest.birth_date:type_name -> google.protobuf.Timestamp
	10, // 6: github.com.nazarovnick.chat_platform.user.UpdateUserRequest.avatar_url:type_name -> google.protobuf.StringValue
	11, // 7: github.com.nazarovnick.chat_platform.user.UpdateUserRequest.soft_deleted:type_name -> google.protobuf.BoolValue
	9,  // 8: github.com.nazarovnick.chat_platform.user.UpdateUserResponse.birth_date:type_name -> google.protobuf.Timestamp
	9,  // 9: github.com.nazarovnick.chat_platform.user.UpdateUserResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 10: github.com.nazarovnick.chat_platform.user.SearchUsersByNicknameResponse.users:type_name -> github.com.nazarovnick.chat_platform.user.User
	9,  // 11: github.com.nazarovnick.chat_platform.user.User.birth_date:type_name -> google.protobuf.Timestamp
	9,  // 12: github.com.nazarovnick.chat_platform.user.User.created_at:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_v1_user_messages_proto_init() }
func file_api_proto_v1_user_messages_proto_init() {
	if File_api_proto_v1_user_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_user_messages_proto_rawDesc), len(file_api_proto_v1_user_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_user_messages_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_user_messages_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_user_messages_proto_msgTypes,
	}.Build()
	File_api_proto_v1_user_messages_proto = out.File
	file_api_proto_v1_user_messages_proto_goTypes = nil
	file_api_proto_v1_user_messages_proto_depIdxs = nil
}
