// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/proto/v1/user/service.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_v1_user_service_proto protoreflect.FileDescriptor

const file_api_proto_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/v1/user/service.proto\x12)github.com.nazarovnick.chat_platform.user\x1a api/proto/v1/user/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xfa\x05\n" +
	"\vUserService\x12\xa3\x01\n" +
	"\aGetUser\x129.github.com.nazarovnick.chat_platform.user.GetUserRequest\x1a:.github.com.nazarovnick.chat_platform.user.GetUserResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/users/{user_uuid}\x12\xcc\x01\n" +
	"\x11GetUserByNickname\x12C.github.com.nazarovnick.chat_platform.user.GetUserByNicknameRequest\x1aD.github.com.nazarovnick.chat_platform.user.GetUserByNicknameResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/users/by-nickname/{nickname}\x12\xaa\x01\n" +
	"\n" +
	"UpdateUser\x12<.github.com.nazarovnick.chat_platform.user.UpdateUserRequest\x1a=.github.com.nazarovnick.chat_platform.user.UpdateUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/api/v1/users/update\x12\xc8\x01\n" +
	"\x15SearchUsersByNickname\x12G.github.com.nazarovnick.chat_platform.user.SearchUsersByNicknameRequest\x1aH.github.com.nazarovnick.chat_platform.user.SearchUsersByNicknameResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/users/searchB\xd8\x03\x92A\xc7\x03\x12\xc0\x02\n" +
	"\x10User Service API\x12\xbb\x01API для управления пользователями, включая создание, обновление, поиск по никнейму и получение профиля.\"3\n" +
	"\x11User Service Team\x12\x1ehttps://github.com/nazarovnick*2\n" +
	"\vMIT License\x12#https://opensource.org/licenses/MIT2\x051.0.0*\x02\x01\x02r~\n" +
	"@Полная документация и исходный код\x12:https://github.com/nazarovnick/chat-platform/services/userZ\v/user/v1;v1b\x06proto3"

var file_api_proto_v1_user_service_proto_goTypes = []any{
	(*GetUserRequest)(nil),                // 0: github.com.nazarovnick.chat_platform.user.GetUserRequest
	(*GetUserByNicknameRequest)(nil),      // 1: github.com.nazarovnick.chat_platform.user.GetUserByNicknameRequest
	(*UpdateUserRequest)(nil),             // 2: github.com.nazarovnick.chat_platform.user.UpdateUserRequest
	(*SearchUsersByNicknameRequest)(nil),  // 3: github.com.nazarovnick.chat_platform.user.SearchUsersByNicknameRequest
	(*GetUserResponse)(nil),               // 4: github.com.nazarovnick.chat_platform.user.GetUserResponse
	(*GetUserByNicknameResponse)(nil),     // 5: github.com.nazarovnick.chat_platform.user.GetUserByNicknameResponse
	(*UpdateUserResponse)(nil),            // 6: github.com.nazarovnick.chat_platform.user.UpdateUserResponse
	(*SearchUsersByNicknameResponse)(nil), // 7: github.com.nazarovnick.chat_platform.user.SearchUsersByNicknameResponse
}
var file_api_proto_v1_user_service_proto_depIdxs = []int32{
	0, // 0: github.com.nazarovnick.chat_platform.user.UserService.GetUser:input_type -> github.com.nazarovnick.chat_platform.user.GetUserRequest
	1, // 1: github.com.nazarovnick.chat_platform.user.UserService.GetUserByNickname:input_type -> github.com.nazarovnick.chat_platform.user.GetUserByNicknameRequest
	2, // 2: github.com.nazarovnick.chat_platform.user.UserService.UpdateUser:input_type -> github.com.nazarovnick.chat_platform.user.UpdateUserRequest
	3, // 3: github.com.nazarovnick.chat_platform.user.UserService.SearchUsersByNickname:input_type -> github.com.nazarovnick.chat_platform.user.SearchUsersByNicknameRequest
	4, // 4: github.com.nazarovnick.chat_platform.user.UserService.GetUser:output_type -> github.com.nazarovnick.chat_platform.user.GetUserResponse
	5, // 5: github.com.nazarovnick.chat_platform.user.UserService.GetUserByNickname:output_type -> github.com.nazarovnick.chat_platform.user.GetUserByNicknameResponse
	6, // 6: github.com.nazarovnick.chat_platform.user.UserService.UpdateUser:output_type -> github.com.nazarovnick.chat_platform.user.UpdateUserResponse
	7, // 7: github.com.nazarovnick.chat_platform.user.UserService.SearchUsersByNickname:output_type -> github.com.nazarovnick.chat_platform.user.SearchUsersByNicknameResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_user_service_proto_init() }
func file_api_proto_v1_user_service_proto_init() {
	if File_api_proto_v1_user_service_proto != nil {
		return
	}
	file_api_proto_v1_user_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_user_service_proto_rawDesc), len(file_api_proto_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_user_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_user_service_proto_depIdxs,
	}.Build()
	File_api_proto_v1_user_service_proto = out.File
	file_api_proto_v1_user_service_proto_goTypes = nil
	file_api_proto_v1_user_service_proto_depIdxs = nil
}
