apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-blue
  labels:
    app: user-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
      version: blue
  template:
    metadata:
      labels:
        app: user
        version: blue
    spec:
      containers:
        - name: user-container
          image: user:blue
          ports:
            - containerPort: 8080