// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/proto/v1/chat/enums.proto

package chat

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TimeFilterDirection defines whether to filter messages
// BEFORE or AFTER the given timestamp.
type TimeFilterDirection int32

const (
	// No direction specified
	TimeFilterDirection_TIME_FILTER_DIRECTION_UNSPECIFIED TimeFilterDirection = 0
	// Filter messages sent before the timestamp
	TimeFilterDirection_TIME_FILTER_DIRECTION_BEFORE TimeFilterDirection = 1
	// Filter messages sent after the timestamp
	TimeFilterDirection_TIME_FILTER_DIRECTION_AFTER TimeFilterDirection = 2
)

// Enum value maps for TimeFilterDirection.
var (
	TimeFilterDirection_name = map[int32]string{
		0: "TIME_FILTER_DIRECTION_UNSPECIFIED",
		1: "TIME_FILTER_DIRECTION_BEFORE",
		2: "TIME_FILTER_DIRECTION_AFTER",
	}
	TimeFilterDirection_value = map[string]int32{
		"TIME_FILTER_DIRECTION_UNSPECIFIED": 0,
		"TIME_FILTER_DIRECTION_BEFORE":      1,
		"TIME_FILTER_DIRECTION_AFTER":       2,
	}
)

func (x TimeFilterDirection) Enum() *TimeFilterDirection {
	p := new(TimeFilterDirection)
	*p = x
	return p
}

func (x TimeFilterDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeFilterDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_chat_enums_proto_enumTypes[0].Descriptor()
}

func (TimeFilterDirection) Type() protoreflect.EnumType {
	return &file_api_proto_v1_chat_enums_proto_enumTypes[0]
}

func (x TimeFilterDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeFilterDirection.Descriptor instead.
func (TimeFilterDirection) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_chat_enums_proto_rawDescGZIP(), []int{0}
}

var File_api_proto_v1_chat_enums_proto protoreflect.FileDescriptor

const file_api_proto_v1_chat_enums_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/v1/chat/enums.proto\x12)github.com.nazarovnick.chat_platform.chat\x1a.protoc-gen-openapiv2/options/annotations.proto*\xab\a\n" +
	"\x13TimeFilterDirection\x12%\n" +
	"!TIME_FILTER_DIRECTION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTIME_FILTER_DIRECTION_BEFORE\x10\x01\x12\x1f\n" +
	"\x1bTIME_FILTER_DIRECTION_AFTER\x10\x02\x1a\xa9\x06\x92A\xa5\x06\n" +
	"\x87\x06EN:\n" +
	"Specifies how to filter messages based on the provided timestamp.\n" +
	"\n" +
	"1.) TIME_FILTER_DIRECTION_UNSPECIFIED: No direction specified\n" +
	"2.) TIME_FILTER_DIRECTION_BEFORE: Filter messages sent before the timestamp\n" +
	"3.) TIME_FILTER_DIRECTION_AFTER: Filter messages sent after the timestamp\n" +
	"\n" +
	"\n" +
	"RU:\n" +
	"Определяет способ фильтрации сообщений по времени.\n" +
	"\n" +
	"1.) TIME_FILTER_DIRECTION_UNSPECIFIED: Направление фильтрации не указано\n" +
	"2.) TIME_FILTER_DIRECTION_BEFORE: Фильтрация сообщений, отправленных до указанного времени\n" +
	"3.) TIME_FILTER_DIRECTION_AFTER: Фильтрация сообщений, отправленных после указанного времени\n" +
	"\x1a\x19ENUM: TimeFilterDirectionB\fZ\n" +
	"/chat;chatb\x06proto3"

var (
	file_api_proto_v1_chat_enums_proto_rawDescOnce sync.Once
	file_api_proto_v1_chat_enums_proto_rawDescData []byte
)

func file_api_proto_v1_chat_enums_proto_rawDescGZIP() []byte {
	file_api_proto_v1_chat_enums_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_chat_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_chat_enums_proto_rawDesc), len(file_api_proto_v1_chat_enums_proto_rawDesc)))
	})
	return file_api_proto_v1_chat_enums_proto_rawDescData
}

var file_api_proto_v1_chat_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_chat_enums_proto_goTypes = []any{
	(TimeFilterDirection)(0), // 0: github.com.nazarovnick.chat_platform.chat.TimeFilterDirection
}
var file_api_proto_v1_chat_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_chat_enums_proto_init() }
func file_api_proto_v1_chat_enums_proto_init() {
	if File_api_proto_v1_chat_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_chat_enums_proto_rawDesc), len(file_api_proto_v1_chat_enums_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_chat_enums_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_chat_enums_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_chat_enums_proto_enumTypes,
	}.Build()
	File_api_proto_v1_chat_enums_proto = out.File
	file_api_proto_v1_chat_enums_proto_goTypes = nil
	file_api_proto_v1_chat_enums_proto_depIdxs = nil
}
