// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: service.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12.github.com.nazarovnick.chat_platform.chat.grpc\x1a\x0emessages.proto2\xbf\x02\n" +
	"\vChatService\x12\x96\x01\n" +
	"\vSendMessage\x12B.github.com.nazarovnick.chat_platform.chat.grpc.SendMessageRequest\x1aC.github.com.nazarovnick.chat_platform.chat.grpc.SendMessageResponse\x12\x96\x01\n" +
	"\vGetMessages\x12B.github.com.nazarovnick.chat_platform.chat.grpc.GetMessagesRequest\x1aC.github.com.nazarovnick.chat_platform.chat.grpc.GetMessagesResponseB\x18Z\x16pkg/api/grpc/chat;chatb\x06proto3"

var file_service_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: github.com.nazarovnick.chat_platform.chat.grpc.SendMessageRequest
	(*GetMessagesRequest)(nil),  // 1: github.com.nazarovnick.chat_platform.chat.grpc.GetMessagesRequest
	(*SendMessageResponse)(nil), // 2: github.com.nazarovnick.chat_platform.chat.grpc.SendMessageResponse
	(*GetMessagesResponse)(nil), // 3: github.com.nazarovnick.chat_platform.chat.grpc.GetMessagesResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: github.com.nazarovnick.chat_platform.chat.grpc.ChatService.SendMessage:input_type -> github.com.nazarovnick.chat_platform.chat.grpc.SendMessageRequest
	1, // 1: github.com.nazarovnick.chat_platform.chat.grpc.ChatService.GetMessages:input_type -> github.com.nazarovnick.chat_platform.chat.grpc.GetMessagesRequest
	2, // 2: github.com.nazarovnick.chat_platform.chat.grpc.ChatService.SendMessage:output_type -> github.com.nazarovnick.chat_platform.chat.grpc.SendMessageResponse
	3, // 3: github.com.nazarovnick.chat_platform.chat.grpc.ChatService.GetMessages:output_type -> github.com.nazarovnick.chat_platform.chat.grpc.GetMessagesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
